---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-pvc
  namespace: ${namespace_name}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

---
apiVersion: v1
kind: Service
metadata:
  name: mattermost-service
  namespace: ${namespace_name}
spec:
  selector:
    app: mattermost
  ports:
  - protocol: TCP
    port: 8065
    targetPort: 8065
    nodePort: ${mattermost_node_port}
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-deployment
  namespace: ${namespace_name}
  labels:
    app: mattermost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
    spec:
      containers:
      - name: mattermost
        image: mattermost/mattermost-team-edition:${mattermost_image_tag}
        ports:
        - containerPort: 8065
        env:
        - name: MM_SQLSETTINGS_DRIVERNAME
          value: postgres
        - name: MM_SQLSETTINGS_DATASOURCE
          value: postgres://mmuser:${db_password}@postgres-service:5432/mattermost?sslmode=disable&connect_timeout=10
        - name: MM_SERVICESETTINGS_SITEURL
          value: http://${node_ip}:${mattermost_node_port}
        - name: MM_SERVICESETTINGS_ENABLELOCALMODE
          value: "true"
        volumeMounts:
        - mountPath: /mattermost/config
          name: mattermost-data
          subPath: config
        - mountPath: /mattermost/data
          name: mattermost-data
          subPath: data
        - mountPath: /mattermost/logs
          name: mattermost-data
          subPath: logs
        - mountPath: /mattermost/plugins
          name: mattermost-data
          subPath: plugins
        - mountPath: /mattermost/client/plugins
          name: mattermost-data
          subPath: client-plugins
        - mountPath: /mattermost/bleve-indexes
          name: mattermost-data
          subPath: bleve-indexes
      volumes:
      - name: mattermost-data
        persistentVolumeClaim:
          claimName: mattermost-pvc