


---
# Service
apiVersion: v1
kind: Service
metadata:
  name: ${kubernetes_name}-service
  namespace: ${namespace_name} 
spec:
  selector:
    app: ${kubernetes_name}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${kubernetes_name}-deployment
  namespace: ${namespace_name} 
  labels:
    app: ${kubernetes_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${kubernetes_name}
  template:
    metadata:
      labels:
        app: ${kubernetes_name}
    spec:
      containers:
      - name: ${container_name}
        image: ${image_and_tag}
        args: ["start-dev"]
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin"

